### ISSUE TITLE
How can I run this piece of code? The Docker container has already been started.

### ISSUE THREAD

**Issue by yingyukexiansheng** [jaypyles/FreeAskInternet-API#4]
How can I run this piece of code? The Docker container has already been started.
`body = {
  "model": "gpt3.5",
  "messages": [{"role": "user", "content": "Why does the moon create the tides"}],
}

url = "http://searchbackend:8000/v1/chat/completions"
response = requests.post(url, json=body)`

**Comment by yingyukexiansheng** [comment]
`Traceback (most recent call last):
  File "/home/lijun/.local/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/lijun/.local/lib/python3.10/site-packages/urllib3/response.py", line 1040, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/lijun/.local/lib/python3.10/site-packages/urllib3/response.py", line 1184, in read_chunked
    self._update_chunk_length()
  File "/home/lijun/.local/lib/python3.10/site-packages/urllib3/response.py", line 1119, in _update_chunk_length
    raise ProtocolError("Response ended prematurely") from None
urllib3.exceptions.ProtocolError: Response ended prematurely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/code/genimg/FreeAskInternet-API/ipython.py", line 39, in <module>
    main()
  File "/mnt/d/code/genimg/FreeAskInternet-API/ipython.py", line 18, in main
    response_text = response.text
  File "/home/lijun/.local/lib/python3.10/site-packages/requests/models.py", line 923, in text
    if not self.content:
  File "/home/lijun/.local/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/lijun/.local/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: Response ended prematurely`

**Comment by jaypyles** [comment]
There was some issues with the gpt4free container I was using, this should be fixed now.
